save_loc: NAF_logs/pra
exp_name: Pra_param_2_1
coor_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF
spec_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/magnitudes
phase_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/phases
mean_std_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/magnitude_mean_std
phase_std_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/preprocess/phase_std
minmax_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/minmax
wav_base: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/raw
split_loc: Pyroomacoustics/outputs/real_env_avr_16kHz_NAF/train_test_split
gpus: 1
dir_ch: 1
max_len: 15
layers: 8
layers_residual: 0
features: 512
epochs: 500
reg_eps: 0.1
lr_init: 0.005
lr_decay: 0.1
phase_alpha: 3.0
mag_alpha: 1.0
batch_norm: main
activation_func_name: default
