save_loc: NAF_logs/real_env_ch_emb
exp_name: Real_env_ch_emb_param_4_1
coor_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF
spec_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/magnitudes
phase_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/phases
mean_std_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/magnitude_mean_std
phase_std_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/preprocess/phase_std
minmax_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/minmax
wav_base: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/raw
split_loc: AcoustiX/custom_scene/real_env_Smooth_concrete_painted/real_env_Smooth_concrete_painted_centered_standard_NAF/train_test_split
gpus: 1
dir_ch: 8
max_len: 15
layers: 8
layers_residual: 0
features: 512
epochs: 500
reg_eps: 0.1
lr_init: 5.0e-05
lr_decay: 0.1
phase_alpha: 3.0
mag_alpha: 1.0
batch_norm: main
activation_func_name: default
